name = "bootstrap-v5"
license = "MIT"
licenselink = "https://github.com/Dzmuh/hugo-bootstrap-v5/blob/master/LICENSE"
description = "bootstrap v5 theme for Hugo"
homepage = "https://github.com/Dzmuh/hugo-bootstrap-v5"
tags = ["multilingual"]
features = ["multilingual"]
min_version = "0.41"

[author]
  name = "dzmuh"
  homepage = "https://github.com/dzmuh/"
